/*
 * Copyright (C) 2026 JLinAlg contributors
 * SPDX-License-Identifier: GPL-2.0-or-later
 */
package org.jlinalg.distributional;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.io.IOException;
import java.io.InputStream;
import java.util.List;
import java.util.Properties;
import org.jlinalg.compute.BackendPolicy;
import org.jlinalg.gam.PenalizedPredictor;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;

/** Independent regression fixtures generated by gamlss and VGAM. */
final class DistributionalRReferenceTest {
    private static Properties reference;

    @BeforeAll
    static void loadReference() throws IOException {
        reference = new Properties();
        try (InputStream input = DistributionalRReferenceTest.class
                .getResourceAsStream(
                    "/r-reference/gamlss-vgam-distributional.properties")) {
            if (input == null) throw new IOException("missing distributional R fixture");
            reference.load(input);
        }
    }

    @Test
    void gaussianLocationScaleMatchesGamlss() {
        int observations = 160;
        double[] response = new double[observations];
        double[][] design = new double[observations][2];
        double normalizer = Math.sqrt(
            (1.0 + 0.55 * 0.55 + 0.25 * 0.25) / 2.0);
        for (int row = 0; row < observations; row++) {
            double x = -1.0 + 2.0 * row / (observations - 1.0);
            double noise = (Math.sin(1.7 * row) + 0.55 * Math.cos(0.43 * row)
                + 0.25 * Math.sin(2.31 * row)) / normalizer;
            response[row] = 1.2 + 0.7 * x
                + Math.exp(-0.4 + 0.3 * x) * noise;
            design[row][0] = 1.0;
            design[row][1] = x;
        }
        PenalizedPredictor predictor = PenalizedPredictor.linear(design);
        DistributionalResult fit = DistributionalModel.fit(response,
            List.of(predictor, predictor),
            DistributionalFamilies.gaussianLocationScale(),
            DistributionalOptions.defaults(), BackendPolicy.CPU);

        assertTrue(fit.converged(), fit.convergenceMessage());
        assertEquals(value("gamlss.mu.intercept"),
            fit.parameter("mu").coefficients()[0], 2e-7);
        assertEquals(value("gamlss.mu.slope"),
            fit.parameter("mu").coefficients()[1], 2e-7);
        assertEquals(value("gamlss.sigma.intercept"),
            fit.parameter("sigma").coefficients()[0], 2e-7);
        assertEquals(value("gamlss.sigma.slope"),
            fit.parameter("sigma").coefficients()[1], 2e-7);
        assertEquals(value("gamlss.logLikelihood"), fit.logLikelihood(), 2e-7);
        assertSelected("gamlss.mu.fitted", fit.parameter("mu").fittedValues());
        assertSelected("gamlss.sigma.fitted",
            fit.parameter("sigma").fittedValues());
    }

    @Test
    void multinomialLogitsAndProbabilitiesMatchVgam() {
        int observations = 180;
        double[] response = new double[observations];
        double[][] design = new double[observations][2];
        long state = 7_654_321L;
        for (int row = 0; row < observations; row++) {
            double x = -1.0 + 2.0 * row / (observations - 1.0);
            double eta0 = 0.2 + 0.7 * x;
            double eta1 = -0.3 - 0.5 * x;
            double denominator = 1.0 + Math.exp(eta0) + Math.exp(eta1);
            double p0 = Math.exp(eta0) / denominator;
            double p1 = Math.exp(eta1) / denominator;
            state = 48_271L * state % 2_147_483_647L;
            double uniform = state / 2_147_483_647.0;
            response[row] = uniform < p0 ? 0.0
                : uniform < p0 + p1 ? 1.0 : 2.0;
            design[row][0] = 1.0;
            design[row][1] = x;
        }
        PenalizedPredictor predictor = PenalizedPredictor.linear(design);
        DistributionalFamily family = DistributionalFamilies.multinomial(3);
        DistributionalResult fit = DistributionalModel.fit(response,
            List.of(predictor, predictor), family,
            DistributionalOptions.defaults(), BackendPolicy.CPU);

        assertTrue(fit.converged(), fit.convergenceMessage());
        assertEquals(value("vgam.logit0.intercept"),
            fit.parameter("logit0").coefficients()[0], 2e-7);
        assertEquals(value("vgam.logit0.slope"),
            fit.parameter("logit0").coefficients()[1], 2e-7);
        assertEquals(value("vgam.logit1.intercept"),
            fit.parameter("logit1").coefficients()[0], 2e-7);
        assertEquals(value("vgam.logit1.slope"),
            fit.parameter("logit1").coefficients()[1], 2e-7);
        assertEquals(value("vgam.logLikelihood"), fit.logLikelihood(), 2e-7);

        double[][] probabilities = DistributionalPrediction.categoryProbabilities(
            fit, List.of(predictor, predictor), family);
        assertEquals(value("vgam.probability.row0.category0"),
            probabilities[0][0], 2e-7);
        assertEquals(value("vgam.probability.row89.category1"),
            probabilities[89][1], 2e-7);
        assertEquals(value("vgam.probability.row179.category2"),
            probabilities[179][2], 2e-7);
    }

    private static void assertSelected(String prefix, double[] actual) {
        assertEquals(value(prefix + "0"), actual[0], 2e-7);
        assertEquals(value(prefix + "79"), actual[79], 2e-7);
        assertEquals(value(prefix + "159"), actual[159], 2e-7);
    }

    private static double value(String key) {
        return Double.parseDouble(reference.getProperty(key));
    }
}
