/*
 * Copyright (C) 2026 JLinAlg contributors
 * SPDX-License-Identifier: GPL-2.0-or-later
 */
package org.jlinalg.gee;

import static org.junit.jupiter.api.Assertions.assertArrayEquals;
import static org.junit.jupiter.api.Assertions.assertEquals;

import org.jlinalg.compute.BackendPolicy;
import org.jlinalg.glm.GlmFamilies;
import org.junit.jupiter.api.Test;

/** Values generated by generate-gee-reference.R with documented package versions. */
class GeeRReferenceTest {
    @Test
    void exchangeableGaussianAgreesWithGeepackAndGeer() {
        int clusters = 18;
        int observations = clusters * 3 - 3;
        double[] response = new double[observations];
        double[][] design = new double[observations][2];
        int[] id = new int[observations];
        int[] repeated = new int[observations];
        int row = 0;
        for (int cluster = 0; cluster < clusters; cluster++) {
            int size = cluster < 3 ? 2 : 3;
            double clusterEffect = (cluster % 5 - 2) * 0.25;
            for (int visit = 0; visit < size; visit++) {
                response[row] = 1.5 + 0.7 * visit + clusterEffect
                    + ((cluster + visit) % 3 - 1) * 0.1;
                design[row][0] = 1.0;
                design[row][1] = visit;
                id[row] = cluster;
                repeated[row] = visit;
                row++;
            }
        }
        GeeResult result = Gee.fit(response, design, id, repeated,
            GlmFamilies.gaussian(), null, null,
            GeeOptions.builder()
                .correlation(GeeCorrelation.EXCHANGEABLE).build(),
            BackendPolicy.CPU);

        // geer 0.1.0 values; geepack 1.3.13 uses a slightly different
        // degrees-of-freedom correction for the nuisance update.
        assertArrayEquals(new double[] {
            1.4581262562943, 0.700621231117102
        }, result.coefficients(), 1e-6);
        assertEquals(0.93931385533466,
            result.associationParameters()[0], 1e-6);
        assertArrayEquals(new double[] {
            0.00713380017751337, -0.000354543839142001,
            -0.000354543839142001, 0.000318894770565153
        }, result.robustCovariance(), 1e-7);
        assertArrayEquals(new double[] {
            0.00871227824290586, -0.000415293889415103,
            -0.000415293889415103, 0.000379679977253081
        }, result.biasCorrectedCovariance(), 8e-4);
    }
}
