/*
 * Copyright (C) 2026 JLinAlg contributors
 * SPDX-License-Identifier: GPL-2.0-or-later
 */
package org.jlinalg.reference;

import static org.junit.jupiter.api.Assertions.assertArrayEquals;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.util.ArrayList;
import java.util.List;
import org.jlinalg.compute.BackendPolicy;
import org.jlinalg.glm.Glm;
import org.jlinalg.glm.GlmFamilies;
import org.jlinalg.glm.GlmOptions;
import org.jlinalg.glm.GlmResult;
import org.jlinalg.mr.HarmonizedInstrument;
import org.jlinalg.mr.MendelianRandomization;
import org.jlinalg.mr.MrEggerResult;
import org.jlinalg.mr.MrEstimate;
import org.jlinalg.mr.MrOptions;
import org.jlinalg.ols.Ols;
import org.jlinalg.ols.OlsOptions;
import org.jlinalg.ols.OlsResult;
import org.jlinalg.pedigree.Pedigree;
import org.jlinalg.pedigree.PedigreeIndividual;
import org.jlinalg.pedigree.PedigreeReml;
import org.jlinalg.pedigree.PedigreeRemlResult;
import org.jlinalg.pedigree.SparsePedigreeReml;
import org.jlinalg.pedigree.SparsePedigreeRemlResult;
import org.jlinalg.reml.Reml;
import org.jlinalg.reml.RemlOptions;
import org.jlinalg.reml.RemlResult;
import org.jlinalg.reml.VarianceComponent;
import org.junit.jupiter.api.Test;

/** Cross-language regression fixtures generated by generate-reference.R. */
class RReferenceTest {
    private static final double[] MTCARS_MPG = {
        21, 21, 22.8, 21.4, 18.7, 18.1, 14.3, 24.4,
        22.8, 19.2, 17.8, 16.4, 17.3, 15.2, 10.4, 10.4,
        14.7, 32.4, 30.4, 33.9, 21.5, 15.5, 15.2, 13.3,
        19.2, 27.3, 26, 30.4, 15.8, 19.7, 15, 21.4
    };
    private static final double[] MTCARS_WT = {
        2.62, 2.875, 2.32, 3.215, 3.44, 3.46, 3.57, 3.19,
        3.15, 3.44, 3.44, 4.07, 3.73, 3.78, 5.25, 5.424,
        5.345, 2.2, 1.615, 1.835, 2.465, 3.52, 3.435, 3.84,
        3.845, 1.935, 2.14, 1.513, 3.17, 2.77, 3.57, 2.78
    };
    private static final double[] MTCARS_HP = {
        110, 110, 93, 110, 175, 105, 245, 62,
        95, 123, 123, 180, 180, 180, 205, 215,
        230, 66, 52, 65, 97, 150, 150, 245,
        175, 66, 91, 113, 264, 175, 335, 109
    };
    private static final double[] MTCARS_AM = {
        1, 1, 1, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0,
        0, 1, 1, 1, 0, 0, 0, 0,
        0, 1, 1, 1, 1, 1, 1, 1
    };
    private static final double[] WARP_BREAKS = {
        26, 30, 54, 25, 70, 52, 51, 26, 67,
        18, 21, 29, 17, 12, 18, 35, 30, 36,
        36, 21, 24, 18, 10, 43, 28, 15, 26,
        27, 14, 29, 19, 29, 31, 41, 20, 44,
        42, 26, 19, 16, 39, 28, 21, 39, 29,
        20, 21, 24, 17, 13, 15, 15, 16, 28
    };
    private static final double[] ERGO_EFFORT = {
        12, 15, 12, 10, 10, 14, 13, 12, 7, 14, 13, 9,
        7, 11, 10, 9, 8, 11, 8, 7, 9, 11, 11, 10,
        8, 12, 12, 11, 7, 11, 8, 7, 9, 13, 10, 8
    };
    private static final double[] PEDIGREE_RESPONSE = {
        8.5, 9.1, 8.9, 9.5, 10.8, 11.4,
        10.4, 11.0, 9.3, 9.9, 10.0, 10.6
    };
    private static final double[] MR_BX = {
        0.026, -0.044, -0.038, -0.023, -0.017, -0.031, -0.018,
        0.046, 0.059, 0.004, 0.011, -0.005, 0.004, 0.022, -0.005,
        -0.002, -0.002, 0.004, 0.011, 0.009, -0.011, -0.003,
        -0.012, 0.0003, -0.015, -0.008, 0.009, -0.036
    };
    private static final double[] MR_BX_SE = {
        0.004, 0.004, 0.004, 0.003, 0.003, 0.006, 0.004,
        0.007, 0.004, 0.003, 0.004, 0.005, 0.005, 0.005, 0.004,
        0.004, 0.003, 0.004, 0.004, 0.003, 0.004, 0.003,
        0.004, 0.003, 0.003, 0.004, 0.003, 0.007
    };
    private static final double[] MR_BY = {
        0.0677, -0.1625, -0.1054, -0.0619, -0.0834, -0.1278, -0.0408,
        0.077, 0.157, -0.0305, 0.01, 0.1823, -0.0408, 0.1989, 0.01,
        0.0488, 0.01, -0.0408, -0.0305, -0.0408, -0.0202, -0.0619,
        0.0296, 0.0677, -0.0726, -0.0726, 0, 0.0198
    };
    private static final double[] MR_BY_SE = {
        0.0286, 0.03, 0.031, 0.0243, 0.0222, 0.0667, 0.0373,
        0.0543, 0.0306, 0.0236, 0.0277, 0.0403, 0.0344, 0.0335,
        0.0378, 0.0292, 0.0253, 0.0319, 0.0316, 0.0241, 0.0285,
        0.0217, 0.0298, 0.0239, 0.022, 0.0246, 0.0255, 0.0647
    };

    @Test
    void olsMatchesRStatsLmOnMtcars() {
        OlsResult result = Ols.fit(MTCARS_MPG, mtcarsDesign(),
            OlsOptions.defaults(), BackendPolicy.CPU);

        assertArrayEquals(new double[] {
            37.2272701164472, -3.87783074240468, -0.031772946982161
        }, result.coefficients(), 2e-12);
        assertArrayEquals(new double[] {
            1.59878753799939, 0.632733494377395, 0.00902970967585572
        }, result.standardErrors(), 2e-12);
        assertArrayEquals(new double[] {
            23.2846886979309, -6.12869521981041, -3.51871191020878
        }, result.tStatistics(), 2e-11);
        assertArrayEquals(new double[] {
            2.56545851198376e-20, 1.11964713620004e-6,
            0.00145122853156942
        }, result.pValues(), 2e-14);
        assertArrayEquals(result.coefficients(),
            result.associationStatistics().beta());
        assertArrayEquals(result.tStatistics(),
            result.associationStatistics().statistics());
        assertEquals(195.047754741466, result.residualSumOfSquares(), 2e-11);
        assertEquals(6.72578464625746, result.residualVariance(), 2e-12);
        assertEquals(-74.3261694128207, result.logLikelihood(), 2e-12);
    }

    @Test
    void binomialGlmMatchesRStatsOnMtcars() {
        GlmResult result = Glm.fit(MTCARS_AM, mtcarsDesign(),
            GlmFamilies.binomial(), null, null,
            GlmOptions.defaults(), BackendPolicy.CPU);

        assertTrue(result.converged(), result.convergenceMessage());
        assertArrayEquals(new double[] {
            18.8662987172041, -8.08347518244463, 0.0362555960822165
        }, result.coefficients(), 2e-7);
        assertArrayEquals(new double[] {
            7.44355806020527, 3.0686751130547, 0.0177341536507693
        }, result.standardErrors(), 6e-7);
        assertEquals(10.059110472267, result.deviance(), 2e-10);
        assertEquals(-5.02955523613349, result.logLikelihood(), 2e-10);
        assertEquals(16.059110472267, result.aic(), 2e-10);
        assertArrayEquals(result.coefficients(),
            result.associationStatistics().beta());
        assertArrayEquals(result.statistics(),
            result.associationStatistics().statistics());
    }

    @Test
    void poissonGlmMatchesRStatsOnWarpbreaks() {
        GlmResult result = Glm.fit(WARP_BREAKS, warpbreaksDesign(),
            GlmFamilies.poisson(), null, null,
            GlmOptions.defaults(), BackendPolicy.CPU);

        assertTrue(result.converged(), result.convergenceMessage());
        assertArrayEquals(new double[] {
            3.69196314495379, -0.205988442648863,
            -0.321320431600191, -0.518488496517343
        }, result.coefficients(), 2e-8);
        assertArrayEquals(new double[] {
            0.0454106925991773, 0.0515711686464422,
            0.0602658019343353, 0.0639594433127196
        }, result.standardErrors(), 2e-7);
        assertEquals(210.391888762454, result.deviance(), 2e-9);
        assertEquals(-242.527983208979, result.logLikelihood(), 2e-9);
        assertEquals(493.055966417958, result.aic(), 2e-9);
    }

    @Test
    void randomInterceptRemlMatchesRnlmeOnErgoStool() {
        double[][] design = ergoDesign();
        double[] group = new double[ERGO_EFFORT.length * ERGO_EFFORT.length];
        for (int row = 0; row < ERGO_EFFORT.length; row++) {
            for (int column = 0; column < ERGO_EFFORT.length; column++) {
                if (row / 4 == column / 4) {
                    group[row * ERGO_EFFORT.length + column] = 1.0;
                }
            }
        }
        RemlResult result = Reml.fit(ERGO_EFFORT, design,
            List.of(
                new VarianceComponent("Subject", ERGO_EFFORT.length, group),
                VarianceComponent.identity("residual", ERGO_EFFORT.length)),
            RemlOptions.builder().initialVariances(1.8, 1.2).build(),
            BackendPolicy.CPU);

        assertTrue(result.converged(), result.convergenceMessage());
        assertArrayEquals(new double[] {
            8.55555555555556, 3.88888888888889,
            2.22222222222222, 0.666666666666666
        }, result.fixedEffects(), 2e-11);
        assertEquals(1.7754629771426, result.varianceComponents()[0], 2e-6);
        assertEquals(1.2106481455221, result.varianceComponents()[1], 2e-6);
        assertArrayEquals(new double[] {
            0.331790124740523, -0.134516460613567,
            -0.134516460613567, -0.134516460613567,
            -0.134516460613567, 0.269032921227134,
            0.134516460613567, 0.134516460613567,
            -0.134516460613567, 0.134516460613567,
            0.269032921227134, 0.134516460613567,
            -0.134516460613567, 0.134516460613567,
            0.134516460613567, 0.269032921227134
        }, result.fixedEffectCovariance(), 2e-7);
    }

    @Test
    void pedigreeRemlMatchesRrBlupMixedSolve() {
        Pedigree pedigree = referencePedigree();
        List<String> observed = List.of(
            "5", "5", "6", "6", "7", "7",
            "8", "8", "9", "9", "10", "10");
        double[][] fixed = new double[PEDIGREE_RESPONSE.length][1];
        for (double[] row : fixed) {
            row[0] = 1.0;
        }
        PedigreeRemlResult result = PedigreeReml.fit(
            PEDIGREE_RESPONSE, fixed, observed, pedigree,
            RemlOptions.builder().initialVariances(0.63, 0.17).build(),
            BackendPolicy.CPU);

        assertTrue(result.reml().converged(), result.reml().convergenceMessage());
        assertEquals(0.630889491183793,
            result.additiveGeneticVariance(), 2e-5);
        assertEquals(0.165592876270457,
            result.residualVariance(), 2e-5);
        assertEquals(9.95, result.reml().fixedEffects()[0], 2e-10);
        assertArrayEquals(new double[] {
            -0.582379540148633, -0.582379540148633,
            0.58237954014863, 0.58237954014863,
            -1.05861548011341, -0.688524305091568,
            1.00536233154045, 0.741777453664518,
            -0.282769111490676, 0.282769111490675
        }, result.breedingValues(), 3e-5);
        assertArrayEquals(new double[] {
            0.534201403189016, 0.534201403189016,
            0.534201403189016, 0.534201403189016,
            0.287161538622491, 0.287161538622491,
            0.287161538622492, 0.287161538622492,
            0.314585097032177, 0.314585097032177
        }, result.predictionErrorVariances(), 3e-5);

        SparsePedigreeRemlResult sparse = SparsePedigreeReml.fit(
            PEDIGREE_RESPONSE, fixed, observed, pedigree,
            RemlOptions.builder().initialVariances(0.63, 0.17)
                .maximumIterations(200).build(), BackendPolicy.CPU);
        assertEquals(0.630889491183793,
            sparse.additiveGeneticVariance(), 3e-5);
        assertEquals(0.165592876270457,
            sparse.residualVariance(), 3e-5);
        assertArrayEquals(result.breedingValues(),
            sparse.breedingValues(), 4e-5);
    }

    @Test
    void mrMatchesCranMendelianRandomizationLdlcExample() {
        List<HarmonizedInstrument> instruments = mrInstruments();
        MrEstimate fixed = MendelianRandomization.ivw(instruments, false, 0.95);
        MrEstimate random = MendelianRandomization.ivw(instruments, true, 0.95);
        MrEggerResult egger = MendelianRandomization.egger(instruments, 0.95);
        MrEstimate median = MendelianRandomization.weightedMedian(
            instruments, new MrOptions(0.95, 2, 20260831L));

        assertEquals(2.83421393887889, fixed.estimate(), 2e-13);
        assertEquals(0.275940525057229, fixed.standardError(), 2e-13);
        assertEquals(99.5304255484988, fixed.cochranQ(), 2e-11);
        assertEquals(2.83421393887889, random.estimate(), 2e-13);
        assertEquals(0.52979948855643, random.standardError(), 2e-13);
        assertEquals(3.25289013194081, egger.slope().estimate(), 2e-12);
        assertEquals(0.770129161393982,
            egger.slope().standardError(), 2e-12);
        assertEquals(-0.0114606656512896, egger.intercept(), 2e-14);
        assertEquals(0.0151883205190355,
            egger.interceptStandardError(), 2e-14);
        assertEquals(97.3975050756926, egger.slope().cochranQ(), 2e-11);
        assertEquals(2.68288346489811, median.estimate(), 2e-13);
    }

    private static double[][] mtcarsDesign() {
        double[][] result = new double[MTCARS_MPG.length][3];
        for (int row = 0; row < result.length; row++) {
            result[row][0] = 1.0;
            result[row][1] = MTCARS_WT[row];
            result[row][2] = MTCARS_HP[row];
        }
        return result;
    }

    private static double[][] warpbreaksDesign() {
        double[][] result = new double[WARP_BREAKS.length][4];
        for (int row = 0; row < result.length; row++) {
            int withinWool = row % 27;
            result[row][0] = 1.0;
            result[row][1] = row >= 27 ? 1.0 : 0.0;
            result[row][2] = withinWool >= 9 && withinWool < 18 ? 1.0 : 0.0;
            result[row][3] = withinWool >= 18 ? 1.0 : 0.0;
        }
        return result;
    }

    private static double[][] ergoDesign() {
        double[][] result = new double[ERGO_EFFORT.length][4];
        for (int row = 0; row < result.length; row++) {
            int type = row % 4;
            result[row][0] = 1.0;
            if (type > 0) {
                result[row][type] = 1.0;
            }
        }
        return result;
    }

    private static Pedigree referencePedigree() {
        return Pedigree.of(List.of(
            PedigreeIndividual.founder("1"),
            PedigreeIndividual.founder("2"),
            PedigreeIndividual.founder("3"),
            PedigreeIndividual.founder("4"),
            new PedigreeIndividual("5", "1", "2"),
            new PedigreeIndividual("6", "1", "2"),
            new PedigreeIndividual("7", "3", "4"),
            new PedigreeIndividual("8", "3", "4"),
            new PedigreeIndividual("9", "5", "7"),
            new PedigreeIndividual("10", "6", "8")));
    }

    private static List<HarmonizedInstrument> mrInstruments() {
        List<HarmonizedInstrument> result = new ArrayList<>(MR_BX.length);
        for (int index = 0; index < MR_BX.length; index++) {
            result.add(new HarmonizedInstrument(
                "variant-" + (index + 1), "A", "C",
                MR_BX[index], MR_BX_SE[index], MR_BY[index], MR_BY_SE[index],
                Double.NaN, Double.NaN, false, false));
        }
        return List.copyOf(result);
    }
}
