.libPaths(c('build/r-library', .libPaths()))
# Base-R matrix algebra: identical fixed covariance and normal inference as Java.
# No package-specific likelihood/dispersion convention is substituted.
options(digits=17)
root <- 'src/test/resources/r-reference'
bx <- c(.22,-.31,.45,.19,-.38)
sx <- c(.03,.04,.035,.025,.045)
by <- sign(bx) * (.08 + .7*abs(bx) + c(.01,-.02,.015,.025,-.01))
sy <- c(.04,.05,.045,.035,.055)
R <- .35^abs(outer(1:5,1:5,'-'))
covxy <- .2*sx*sy
write.table(data.frame(variant_id=paste0('rs',1:5),beta_exposure=bx,
  se_exposure=sx,beta_outcome=by,se_outcome=sy),
  file.path(root,'mr-conditional-input.tsv'),sep='\t',row.names=FALSE,quote=FALSE)
write.table(R,file.path(root,'mr-conditional-ld.tsv'),sep='\t',row.names=FALSE,col.names=FALSE)
infer <- function(b,se,level) c(beta=b,se=se,p=2*pnorm(-abs(b/se)),
  lower=b-qnorm(.5+level/2)*se,upper=b+qnorm(.5+level/2)*se)
conditional <- function(C, level=.9) {
  # Refit each augmented joint regression independently as an oracle.
  t(sapply(seq_along(bx),function(j) {
    J <- c(j,setdiff(C,j)); V <- solve(R[J,J,drop=FALSE])
    theta <- V %*% (bx[J]/sx[J])
    infer(sx[j]*theta[1],sx[j]*sqrt(V[1,1]),level)
  }))
}
generalized <- function(egger=FALSE,random=FALSE,level=.9) {
  S <- diag(sy) %*% R %*% diag(sy)
  X <- matrix(bx,ncol=1); y <- by
  if (egger) {
    D <- diag(sign(bx)); S <- D %*% S %*% D
    X <- cbind(1,abs(bx)); y <- sign(bx)*by
  }
  W <- solve(S); V <- solve(t(X)%*%W%*%X)
  b <- drop(V%*%t(X)%*%W%*%y); e <- y-drop(X%*%b)
  Q <- drop(t(e)%*%W%*%e)
  dispersion <- if(egger || random) max(1,Q/(length(y)-ncol(X))) else 1
  rbind(infer(tail(b,1),sqrt(tail(diag(V),1)*dispersion),level),
    if(egger) infer(b[1],sqrt(V[1,1]*dispersion),level) else NULL)
}
overlap <- function(level=.9) {
  b <- sum(bx*by/sy^2)/sum(bx^2/sy^2)
  for (it in 1:100) {
    w <- 1/(sy^2+b^2*sx^2-2*b*covxy)
    nextb <- sum(w*bx*by)/sum(w*bx^2)
    if(abs(nextb-b)<=1e-10*(1+abs(b))) {b <- nextb; break}
    b <- nextb
  }
  stopifnot(it<100)
  w <- 1/(sy^2+b^2*sx^2-2*b*covxy)
  infer(b,sqrt(1/sum(w*bx^2)),level)
}
rows <- rbind(conditional(c(1,3)),conditional(1:5),generalized(),
  generalized(random=TRUE),generalized(egger=TRUE),overlap())
labels <- c(paste0('conditional.',1:5),paste0('joint.',1:5),
  'ivw.fixed','ivw.random','egger.slope','egger.intercept','overlap')
con <- file(file.path(root,'mr-conditional.properties'),'w')
writeLines(c('# Generated by generate-mr-conditional-reference.R with R 4.6.1',
  '# Conditional score model and MR estimating equations, confidence=0.90'),con)
for(i in seq_len(nrow(rows))) for(j in seq_len(ncol(rows)))
  writeLines(sprintf('%s.%s=%.17g',labels[i],colnames(rows)[j],rows[i,j]),con)
close(con)
# Independently refit augmented regressions after each lead change.
selectionR <- matrix(c(1,.65,.65,.65,1,0,.65,0,1),3,3)
selectionZ <- c(13,10,10); ids <- c('proxy','causal1','causal2')
selected <- integer(); history <- character()
selectionTests <- function(C) t(sapply(1:3,function(j) {
  J <- c(j,setdiff(C,j)); V <- solve(selectionR[J,J,drop=FALSE])
  infer(.1*drop(V%*%selectionZ[J])[1],.1*sqrt(V[1,1]),.95)
}))
for(iteration in 1:20) {
  tests <- selectionTests(selected)
  if(length(selected) && any(tests[selected,'p']>.05)) {
    worst <- selected[which.max(tests[selected,'p'])]
    selected <- setdiff(selected,worst); history <- c(history,paste('remove',ids[worst]))
  } else {
    candidates <- setdiff(which(tests[,'p']<=.05),selected)
    if(!length(candidates)) break
    best <- candidates[which.max(abs(tests[candidates,'beta']/tests[candidates,'se']))]
    selected <- c(selected,best); history <- c(history,paste('add',ids[best]))
  }
}
stopifnot(iteration<20,identical(selected,c(2L,3L)))
con <- file(file.path(root,'mr-conditional.properties'),'a')
writeLines(paste0('selection.history=',paste(history,collapse=',')),con)
writeLines(paste0('selection.ids=',paste(ids[selected],collapse=',')),con)
tests <- selectionTests(selected)
for(i in 1:3) for(j in seq_len(ncol(tests)))
  writeLines(sprintf('selection.%d.%s=%.17g',i,colnames(tests)[j],tests[i,j]),con)
close(con)
# Independent individual-design check with known residual SD=1.
# crossprod(X)=diag(1/sx) R diag(1/sx), crossprod(X,y)=bx/sx^2.
X <- chol(diag(1/sx)%*%R%*%diag(1/sx))
y <- solve(t(X),bx/sx^2)
stopifnot(max(abs(coef(lm(y~X-1))-conditional(1:5)[,'beta'])) < 1e-12)
reps <- 20000L
for(kind in c('conditional','generalized','egger','overlap')) {
  f <- switch(kind,conditional=function() conditional(c(1,3)),
    generalized=function() generalized(),egger=function() generalized(egger=TRUE),overlap=overlap)
  for(i in 1:2000) invisible(f())
  checksum <- 0
  elapsed <- system.time(for(i in 1:reps) checksum <- checksum+sum(f()))[['elapsed']]
  cat(sprintf('%s R repetitions=%d seconds=%.6f checksum=%.12g\n',kind,reps,elapsed,checksum))
}
