.libPaths(c('build/r-library', .libPaths()))
# Independent base-R references: enumerate distinct coloc configurations,
# one-effect normal-normal posterior, GRM crossproduct, and conditional MLE.
# No coloc/susieR package is required; this is NOT a package-speed comparison.
options(digits=17)
lse <- function(x) { m <- max(x); if(!is.finite(m)) return(m); m+log(sum(exp(x-m))) }
coloc_ref <- function(a,b,w1=rep(1,length(a)),w2=rep(1,length(b))) {
  n <- length(a); p1 <- 1e-4; p2 <- 1e-4; p12 <- 5e-6
  x <- a+log(n*p1)+log(w1)-lse(log(w1))
  y <- b+log(n*p2)+log(w2)-lse(log(w2))
  joint <- outer(x,y,'+')
  h <- c(0,lse(x),lse(y),lse(joint[row(joint)!=col(joint)]),
         log(p12)-log(p1)-log(p2)+lse(diag(joint)))
  shared <- diag(joint); z <- lse(shared)
  c(exp(h-lse(h)),if(is.finite(z))exp(shared-z) else rep(0,n))
}
ser <- function(z,n=400,V=.2) {
  df <- n-1; xty <- df*z/sqrt(z*z+n-2); se2 <- 1/df
  shrink <- V/(V+se2); mu <- shrink*xty/df
  bf <- .5*(log(se2/(se2+V))+(xty/df)^2*V/(se2*(se2+V)))
  alpha <- exp(bf-lse(bf)); c(alpha,alpha*mu,bf)
}
winner <- function(t,c) {
  # Independent Brent root solver for the exact conditional likelihood score.
  # Direct optimize(logLik) loses ~3e-7 here because the likelihood is flat.
  score <- function(mu) {
    logp <- lse(c(pnorm(c-mu,lower.tail=FALSE,log.p=TRUE),pnorm(c+mu,lower.tail=FALSE,log.p=TRUE)))
    t-mu-exp(dnorm(c-mu,log=TRUE)-logp)+exp(dnorm(c+mu,log=TRUE)-logp)
  }
  uniroot(score,c(0,t),tol=1e-12)$root
}
out <- numeric()
add <- function(key,x) { names(x) <- paste0(key,'.',seq_along(x)-1L); out <<- c(out,x) }
add('disjoint',coloc_ref(c(100,-Inf),c(-Inf,100)))
add('dominant',coloc_ref(c(1000,950),c(1000,950)))
add('weighted',coloc_ref(c(2,-1,.5),c(1,.2,-.5),c(1,2,3),c(3,1,2)))
add('winner',vapply(c(5.46,6,40.01,41),function(t)winner(t,if(t>10)40 else 5.45),0.0))
mixture_ll <- function(beta,pi) {
  r <- c(-400,0,400)-beta; v <- 1+beta^2*1e-12
  sum(vapply(r,function(x)lse(c(log(pi)+dnorm(x,sd=sqrt(v),log=TRUE),log1p(-pi)+dnorm(x,sd=sqrt(v+.01),log=TRUE))),0.0))
}
grid <- seq(-1200,1200,length.out=101)
profile <- vapply(grid,function(beta)max(vapply(seq(.05,.95,.05),function(pi)mixture_ll(beta,pi),0.0)),0.0)
best <- which.max(profile); step <- grid[2]-grid[1]
add('mixture',c(grid[best],profile[best],1/sqrt(-(profile[best+1]-2*profile[best]+profile[best-1])/step^2)))
# Independent bounded likelihood maximization on each side of independence.
ld_ll <- function(t) 4*log(t)+4*log(.5-t)+100*log(2*(t*t+(.5-t)^2))
t <- optimize(ld_ll,c(.25,.5),maximum=TRUE,tol=1e-12)$maximum
add('ld_symmetric',c(16*(t-.25)^2,ld_ll(t),96/104))
p <- 64; a <- 5*sin(seq_len(p)*.37)+.1*seq_len(p); b <- 4*cos(seq_len(p)*.23)+.07*seq_len(p)
add('coloc64',coloc_ref(a,b))
z <- 5*sin(seq_len(32)*.37)
add('ser32',ser(z))
dosage <- matrix(c(0,1,2, 0,NA,2, 1,2,0),3,3,byrow=TRUE)
means <- rowMeans(dosage,na.rm=TRUE); sd <- sqrt(means*(1-means/2))
g <- (dosage-means)/sd; g[is.na(g)] <- 0
add('grm',as.vector(t(crossprod(g)/nrow(g))))
path <- 'src/test/resources/r-reference/genetic-audit-reference.properties'
writeLines(c('# Generated by generate-genetic-audit-reference.R; base R independent equations',paste0(names(out),'=',format(out,digits=17,scientific=TRUE,trim=TRUE))),path)
timing <- function(label,f,reps=200L) {
  for(i in seq_len(30)) f()
  times <- numeric(5); checksum <- 0
  for(batch in seq_len(5)) {
    elapsed <- system.time(for(i in seq_len(reps)) { value <- f(); checksum <- checksum+sum(value^2*seq_along(value)) })[['elapsed']]
    times[batch] <- elapsed*1000/reps
  }
  cat(sprintf('%s median_ms=%.9g checksum=%.17g calls=%d\n',label,median(times),checksum,5L*reps))
}
timing('coloc64_baseR_enumeration',function()coloc_ref(a,b))
timing('SER32_baseR_closed_form',function()ser(z),10000L)
timing('winner40_baseR_score',function()winner(40.01,40),1000L)
timing('GRM3_baseR_crossprod',function()as.vector(t(crossprod(g)/nrow(g))),20000L)
cat(R.version.string,'\n')
