.libPaths(c('build/r-library', .libPaths()))
suppressPackageStartupMessages(library(pedigreemm))
options(digits = 17)

ids <- c('A', 'B', 'C', 'D', 'E', 'S1', 'S2', 'H1', 'C1', 'C2', 'I1',
         'U1')
sire <- c(NA, NA, NA, NA, NA, 'A', 'A', 'A', 'S1', 'E', 'C1', 'I1')
dam <- c(NA, NA, NA, NA, NA, 'B', 'B', 'C', 'D', 'S2', 'C2', NA)
ped <- pedigree(sire = sire, dam = dam, label = ids)

A <- as.matrix(getA(ped))
F <- inbreeding(ped)
Ainv <- as.matrix(getAInv(ped))
stopifnot(max(abs(A %*% Ainv - diag(length(ids)))) < 1e-14)
stopifnot(A['S1', 'S2'] == 0.5)
stopifnot(A['S1', 'H1'] == 0.25)
stopifnot(A['C1', 'C2'] == 0.125)
stopifnot(F[match('I1', ids)] == 0.0625)
stopifnot(F[match('U1', ids)] == 0)

numbers <- function(value) {
  paste(format(value, digits = 17, scientific = TRUE, trim = TRUE),
        collapse = ',')
}
output <- c(
  '# Generated by generate-pedigreemm-hierarchy-reference.R',
  paste0('R.version=', getRversion()),
  paste0('pedigreemm.version=', packageVersion('pedigreemm')),
  paste0('Matrix.version=', packageVersion('Matrix')),
  paste0('ids=', paste(ids, collapse = ',')),
  paste0('sire=', paste(ifelse(is.na(sire), '0', sire), collapse = ',')),
  paste0('dam=', paste(ifelse(is.na(dam), '0', dam), collapse = ',')),
  paste0('A=', numbers(as.vector(t(A)))),
  paste0('F=', numbers(as.vector(F))),
  paste0('Ainv=', numbers(as.vector(t(Ainv))))
)
writeLines(output,
  'src/test/resources/r-reference/pedigreemm-hierarchy.properties')
