# Regenerates the observed-variable SEM fixture against lavaan.
local_library <- normalizePath(".r-reference-lib", winslash = "/", mustWork = TRUE)
.libPaths(c(local_library, .libPaths()))
suppressPackageStartupMessages(library(lavaan))

set.seed(20260904)
n <- 750L
x <- rnorm(n)
w <- 0.25 * x + sqrt(1 - 0.25^2) * rnorm(n)
errors <- cbind(rnorm(n), rnorm(n)) %*%
  chol(matrix(c(0.64, 0.12, 0.12, 0.49), 2L, 2L))
m <- 0.45 * x - 0.20 * w + errors[, 1L]
y <- 0.30 * x + 0.55 * m + errors[, 2L]
z <- 0.50 * y + 0.60 * rnorm(n)
data <- data.frame(x, w, m, y, z)

model <- '
  m ~ x + w
  y ~ m + x
  z ~ y
  x ~~ w
  m ~~ y
'
fit <- sem(model, data = data, meanstructure = FALSE, fixed.x = FALSE,
  auto.cov.y = FALSE, estimator = "ML", information = "expected",
  se = "standard")
stopifnot(lavInspect(fit, "converged"))
parameters <- parameterEstimates(fit)
parameters <- parameters[parameters$op %in% c("~", "~~"), ]
labels <- ifelse(parameters$op == "~",
  paste0(parameters$lhs, "~", parameters$rhs),
  paste0(parameters$lhs, "~~", parameters$rhs))
sample_covariance <- cov(data) * (n - 1) / n
measures <- fitMeasures(fit, c("logl", "chisq", "df", "cfi", "tli", "rmsea", "srmr"))

cat("# Generated by generate-sem-reference.R with lavaan ",
  as.character(packageVersion("lavaan")), "\n", sep = "")
cat("observations=", n, "\n", sep = "")
cat("covariance=", paste(format(as.vector(t(sample_covariance)),
  digits = 17L, scientific = FALSE, trim = TRUE), collapse = ","), "\n", sep = "")
for (index in seq_len(nrow(parameters))) {
  key <- gsub("~", "_", labels[[index]], fixed = TRUE)
  cat(key, ".estimate=", format(parameters$est[[index]], digits = 17L),
    "\n", sep = "")
  cat(key, ".se=", format(parameters$se[[index]], digits = 17L),
    "\n", sep = "")
}
for (name in names(measures))
  cat(name, "=", format(measures[[name]], digits = 17L), "\n", sep = "")
